### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by strugee**
In particular note that I assumed two things:
1. Semicolons are preferred. It was kind of hard to tell, since usage is so inconsistent.
2. The license is the Mozilla Public License 2.0. The only indication of the license was in `package.json`, which said the license was "MPL". That doesn't specify a version, so I assumed the latest version of what the usual expansion of "MPL" is.

Also, this PR includes commits from #6. I apparently forgot to `git checkout master` before starting this - sorry about that. If it's an issue I can rebase.

### CODE REVIEW

**Comment by strugee** [comment]
Rebased on top of latest `master`. @mikemaccana ping?

**Comment by mikemaccana** [comment]
Thanks @strugee . Will publish now!

**Comment by mikemaccana** [comment]
Also see .jshintrc re: semicolons. But nevermind!

**Comment by strugee** [comment]
@mikemaccana whoops! Didn't see that. At least it's consistent now :)

Re: contributor, will do, thanks!

**Pull request merged**
